blank_issues_enabled: false
contact_links:
  - name: Help & Support
    url: https://vaultkind.dev
    about: VaultKind help and project information
  - name: User Manual
    url: https://vaultkind.dev
    about: Read the VaultKind documentation here
